<script setup lang="ts">
// @ts-nocheck
import AppConfirmDialog from '../../components/modal/AppConfirmDialog.vue'
import AppModal from '../../components/modal/AppModal.vue'
import BatchCopyDialog from '../../features/admin-batch/components/BatchCopyDialog.vue'
import BatchCreationPanel from '../../features/admin-batch/components/BatchCreationPanel.vue'
import { useAdminBatchView } from './AdminBatchView.logic'

const {
  batches,
  ruleTemplates,
  error,
  message,
  allocationPreview,
  allocationBatchId,
  allocationSummary,
  unassignedStudents,
  roomPreflight,
  preflightBatch,
  preflightRooms,
  preflightBlockers,
  preflightMissingSteps,
  copyDialog,
  copying,
  copySource,
  copyForm,
  scopeDialog,
  scopeLoading,
  scopeSaving,
  scopeBatch,
  selectedStudentIds,
  selectedRoomIds,
  studentFilter,
  studentGenderFilter,
  studentCategoryFilter,
  studentDegreeFilter,
  studentMajorFilter,
  studentGradeFilter,
  roomFilter,
  roomGenderFilter,
  roomScopeFilter,
  roomBuildingFilter,
  roomFloorFilter,
  publishAfterScope,
  publishConfirmation,
  publishPreflightSnapshot,
  publishFlowState,
  publishFlowBusy,
  creatingDraft,
  runningPreflight,
  publishing,
  form,
  bedModeAuthorized,
  ruleTemplateSummary,
  scopeMajorOptions,
  scopeGradeOptions,
  scopeBuildingOptions,
  scopeFloorOptions,
  filteredStudents,
  filteredRooms,
  createBatch,
  openScope,
  closeScope,
  toggleStudent,
  toggleRoom,
  selectAllStudents,
  selectAllRooms,
  saveScope,
  saveScopeAndContinuePublish,
  preflight,
  closePreflight,
  reopenScopeFromPreflight,
  closePublishConfirmation,
  confirmPublish,
  changeStatus,
  openCopy,
  closeCopy,
  copyBatch,
  previewAllocation,
  commitAllocation,
  download,
  nextActions,
  modeText,
  statusText,
  actionText,
  issueText,
  formatDateTime,
  batchRuleSummary,
} = useAdminBatchView()
</script>

<template src="./AdminBatchView.template.html"></template>

<style scoped src="./AdminBatchView.css"></style>
