<script setup lang="ts">
// @ts-nocheck
import ImportWorkflowModal from '../../components/admin/ImportWorkflowModal.vue'
import PhoneDialCodeSelect from '../../components/common/PhoneDialCodeSelect.vue'
import PaginationBar from '../../components/common/PaginationBar.vue'
import TransientNotice from '../../components/common/TransientNotice.vue'
import RoomBedScene3D from '../../components/student/RoomBedScene3D.vue'
import { useAdminDataView } from './AdminDataView.logic'

const {
  computed,
  onMounted,
  reactive,
  ref,
  api,
  countryLabel,
  countryOptions,
  domesticRegionOptions,
  dialCodeForCountry,
  formatPhoneDisplay,
  normalizeInternationalPhone,
  splitInternationalPhone,
  bedTypeLabel,
  useI18n,
  currentYear,
  majors,
  students,
  total,
  page,
  pageSize,
  keyword,
  categoryFilter,
  error,
  notice,
  noticeType,
  loading,
  editingStudent,
  savingStudent,
  importOpen,
  resetTarget,
  resetMode,
  resetting,
  placementTarget,
  placementLoadingId,
  placementSaving,
  placementRoomId,
  phoneDialCode,
  majorForm,
  resetForm,
  placementForm,
  studentForm,
  subtitle,
  translateError,
  enabledMajors,
  selectableCountries,
  placementBeds,
  placementRooms,
  placementRoomBeds,
  placementSceneBeds,
  currentResidency,
  load,
  showNotice,
  searchStudents,
  createMajor,
  toggleMajor,
  setStudentCategory,
  syncDialCode,
  studentPayload,
  saveStudent,
  fillStudentForm,
  editStudent,
  closeStudentEdit,
  resetStudentForm,
  downloadTemplate,
  importCommitted,
  openReset,
  closeReset,
  submitReset,
  openPlacement,
  closePlacement,
  savePlacement,
  choosePlacementRoom,
  selectPlacementBed,
  closePlacementAfterSave,
  categoryText,
  degreeText,
  sourceText
} = useAdminDataView()
</script>

<template src="./AdminDataView.template.html"></template>

<style scoped src="./AdminDataView.css"></style>
