<script setup lang="ts">
// @ts-nocheck
import { useAdminBatchView } from './AdminBatchView.logic'

const {
  computed,
  nextTick,
  onMounted,
  reactive,
  ref,
  api,
  useFeatureAccess,
  hasFeature,
  batches,
  ruleTemplates,
  error,
  message,
  allocationPreview,
  allocationBatchId,
  roomPreflight,
  preflightBatch,
  copyDialog,
  copying,
  copySource,
  scopeDialog,
  scopeLoading,
  scopeSaving,
  scopeBatch,
  scopeData,
  selectedStudentIds,
  selectedRoomIds,
  studentFilter,
  studentGenderFilter,
  studentCategoryFilter,
  studentDegreeFilter,
  studentMajorFilter,
  studentGradeFilter,
  roomFilter,
  roomGenderFilter,
  roomScopeFilter,
  roomBuildingFilter,
  roomFloorFilter,
  publishAfterScope,
  publishConfirmation,
  publishPreflightSnapshot,
  publishing,
  form,
  copyForm,
  bedModeAuthorized,
  selectedRuleTemplate,
  ruleTemplateSummary,
  preflightRooms,
  preflightBlockers,
  allocationSummary,
  unassignedStudents,
  scopeStudents,
  scopeRooms,
  scopeMajorOptions,
  scopeGradeOptions,
  scopeBuildingOptions,
  scopeFloorOptions,
  filteredStudents,
  filteredRooms,
  load,
  createBatch,
  openScope,
  closeScope,
  resetScopeDialog,
  toggleStudent,
  toggleRoom,
  selectAllStudents,
  selectAllRooms,
  toggleId,
  uniqueIds,
  saveScope,
  preflight,
  reopenScopeFromPreflight,
  openPublishConfirmationAfterPreflight,
  closePublishConfirmation,
  preparePublish,
  confirmPublish,
  changeStatus,
  openCopy,
  closeCopy,
  copyBatch,
  previewAllocation,
  commitAllocation,
  download,
  run,
  nextActions,
  modeText,
  statusText,
  actionText,
  issueText
} = useAdminBatchView()
</script>

<template src="./AdminBatchView.template.html"></template>

<style scoped src="./AdminBatchView.css"></style>
