<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api } from '../../api/client'
import type { DataObject, ObjectSuccessResponse } from '../../api/types'
import { useI18n } from '../../i18n'

const overview = ref<DataObject>({})
const health = ref<DataObject>({})
const preview = ref<DataObject | null>(null)
const loading = ref(true)
const error = ref('')
const form = reactive({ batchId: 0, randomSeed: 2026 })
const { subtitle, translateError } = useI18n()

onMounted(load)
async function load(){loading.value=true;error.value='';try{const[overviewResponse,healthResponse]=await Promise.all([api.get<ObjectSuccessResponse>('/api/v1/admin/operations/overview'),api.get<ObjectSuccessResponse>('/api/v1/admin/operations/health')]);overview.value=(overviewResponse.data.data??{})as DataObject;health.value=(healthResponse.data.data??{})as DataObject}catch(cause){error.value=translateError(cause)}finally{loading.value=false}}
async function loadPreview(){if(!form.batchId)return;try{const response=await api.get<ObjectSuccessResponse>(`/api/v1/admin/batches/${form.batchId}/allocation/optimized-preview`,{params:{randomSeed:form.randomSeed}});preview.value=(response.data.data??{})as DataObject}catch(cause){error.value=translateError(cause)}}
function number(value:unknown){return Number(value??0).toLocaleString()}
</script>

<template><div class="content-column"><header class="page-title split-title"><div><span class="eyebrow">{{subtitle('运营分析','OPERATIONS')}}</span><h2>运营与健康</h2><p>集中查看床位利用率、未选学生、人工调整、运行依赖和统一分配公平性。</p></div><button class="button secondary" :disabled="loading" @click="load">刷新</button></header><p v-if="error" class="alert error">{{error}}</p>
<section class="metric-grid"><article class="panel metric-card"><span>启用床位利用率</span><strong>{{overview.bedUtilization?.rate??0}}%</strong><small>{{number(overview.bedUtilization?.occupiedBeds)}} / {{number(overview.bedUtilization?.enabledBeds)}} 张床</small></article><article class="panel metric-card"><span>未选学生</span><strong>{{number(overview.unselectedStudents)}}</strong><small>活动或已关闭批次中仍未入住</small></article><article class="panel metric-card"><span>人工调整</span><strong>{{number(overview.manualAdjustments)}}</strong><small>换床与换寝历史事件</small></article><article class="panel metric-card"><span>待审换寝</span><strong>{{number(overview.pendingRoomChanges)}}</strong><small>需要管理员处理</small></article><article class="panel metric-card"><span>床位待确认</span><strong>{{number(overview.unknownBedResidents)}}</strong><small>已住寝室但未确认具体床位</small></article><article class="panel metric-card"><span>活动批次</span><strong>{{number(overview.activeBatches)}}</strong><small>已发布、开放或暂停</small></article></section>
<section class="panel health-panel"><div class="section-head"><div><span class="eyebrow">运行健康</span><h3>核心依赖和状态</h3></div><span class="health-badge" :class="{ok:health.healthy}">{{health.healthy?'运行正常':'需要检查'}}</span></div><div class="health-grid"><article><span>MySQL数据库</span><strong>{{health.databaseAvailable?'正常':'不可用'}}</strong></article><article><span>Redis临时占用</span><strong>{{health.redisAvailable?'正常':'不可用'}}</strong></article><article><span>活动寝室锁</span><strong>{{number(health.activeRoomLocks)}}</strong></article><article><span>活动学生锁</span><strong>{{number(health.activeStudentLocks)}}</strong></article><article><span>未确认床位在住</span><strong>{{number(health.unconfirmedResidencies)}}</strong></article></div><details><summary>查看大表与慢查询候选</summary><div class="table-wrap"><table><thead><tr><th>表</th><th>估算行数</th><th>数据与索引字节</th><th>建议</th></tr></thead><tbody><tr v-for="item in (health.slowQueryCandidates??[])" :key="String(item.table_name)"><td>{{item.table_name}}</td><td>{{number(item.estimated_rows)}}</td><td>{{number(item.total_bytes)}}</td><td>{{item.recommendation}}</td></tr></tbody></table></div></details></section>
<section class="panel"><div class="section-head"><div><span class="eyebrow">统一分配评估</span><h3>公平性预演</h3><p>只读取候选结果并计算得分离散程度，不写入正式分配。</p></div></div><form class="preview-form" @submit.prevent="loadPreview"><label><span>批次编号</span><input v-model.number="form.batchId" class="input" type="number" min="1" required/></label><label><span>随机种子</span><input v-model.number="form.randomSeed" class="input" type="number" required/></label><button class="button primary">运行预演</button></form><div v-if="preview" class="preview-result"><article><span>平均得分</span><strong>{{preview.fairness?.averageScore}}</strong></article><article><span>最低得分</span><strong>{{preview.fairness?.minimumScore}}</strong></article><article><span>标准差</span><strong>{{preview.fairness?.standardDeviation}}</strong></article><article><span>公平性指数</span><strong>{{preview.fairness?.fairness}}</strong></article><article><span>已分配</span><strong>{{preview.fairness?.assignedCount}}</strong></article><article><span>未分配</span><strong>{{preview.fairness?.unassignedCount}}</strong></article><p>{{preview.notice}}</p></div></section></div></template>

<style scoped>.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.metric-card{display:grid;gap:5px}.metric-card span{color:var(--muted)}.metric-card strong{font-size:28px}.metric-card small{color:var(--muted)}.health-panel{display:grid;gap:16px}.health-badge{padding:6px 10px;border-radius:999px;background:#fff0f0;color:#a33}.health-badge.ok{background:#eafaf2;color:#16734f}.health-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.health-grid article,.preview-result article{padding:14px;border:1px solid var(--line);border-radius:14px;background:var(--soft)}.health-grid span,.preview-result span{display:block;color:var(--muted);font-size:12px}.health-grid strong,.preview-result strong{display:block;margin-top:5px}.preview-form{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end}.preview-form label{display:grid;gap:6px}.preview-result{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-top:16px}.preview-result p{grid-column:1/-1;color:var(--muted)}details summary{cursor:pointer;font-weight:700}@media(max-width:1000px){.metric-grid{grid-template-columns:repeat(2,1fr)}.health-grid,.preview-result{grid-template-columns:repeat(3,1fr)}}@media(max-width:640px){.metric-grid,.health-grid,.preview-result,.preview-form{grid-template-columns:1fr}}</style>
