/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 激活学生账号 */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前登录用户 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/welcome/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认学生首次登录欢迎信息 */
        post: operations["acknowledgeStudentWelcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings/student-welcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取学生首次登录多语言欢迎语 */
        get: operations["getStudentWelcomeSetting"];
        /** 更新学生首次登录多语言欢迎语 */
        put: operations["updateStudentWelcomeSetting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/majors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMajors"];
        put?: never;
        post: operations["createMajor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/majors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMajor"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStudents"];
        put?: never;
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateStudent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/students/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importStudents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBuildings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRoom"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rooms/{roomId}/bed-layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRoomBedLayout"];
        put: operations["updateRoomBedLayout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/matching-weight-schemes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询匹配权重方案及修订 */
        get: operations["listMatchingWeightSchemes"];
        put?: never;
        /** 创建匹配权重方案首个修订 */
        post: operations["createMatchingWeightScheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/matching-weight-schemes/{schemeId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 基于已有方案创建不可变新修订 */
        post: operations["createMatchingWeightSchemeRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBatches"];
        put?: never;
        post: operations["createBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/batches/{batchId}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["copyBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/batches/{batchId}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["prepareBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/batches/{batchId}/status/{targetStatus}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeBatchStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/batches/{batchId}/allocation/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["previewAllocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/batches/{batchId}/allocation/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commitAllocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/batches/{batchId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询批次当前有效分配 */
        get: operations["listAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/assignments/{assignmentId}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理员调整已分配床位 */
        post: operations["adjustAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/batches/{batchId}/assignments.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentProfile"];
        /** 学生修改本人手机号码 */
        put: operations["updateStudentPhoneNumber"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStudentBatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/questionnaire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestionnaire"];
        put?: never;
        post: operations["submitQuestionnaire"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCandidateRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCandidateRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/personal-selection/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出当前队伍并进入个人选寝 */
        post: operations["preparePersonalSelection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/beds/{bedId}/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["holdBed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/beds/{bedId}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["releaseBed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/beds/{bedId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmBed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/random-recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRandomRecommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyAssignment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/team-invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeamInvitations"];
        put?: never;
        post: operations["inviteTeammate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/team-invitations/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respondTeamInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/teams/{teamId}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["lockTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/teams/{teamId}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/teams/{teamId}/members/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 邀请发起人移除已接受队友 */
        delete: operations["removeTeamMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/teams/{teamId}/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["holdTeamBeds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/teams/{teamId}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["releaseTeamBeds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/batches/{batchId}/teams/{teamId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmTeamBeds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/realtime/batches/{batchId}/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订阅房间级床位状态变化
         * @description 建立服务器发送事件长连接，页面离开时客户端主动关闭。
         */
        get: operations["subscribeRoomEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        ApiResponseMetadata: {
            success: boolean;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
        };
        WelcomeData: {
            required: boolean;
            title: string;
            messages: {
                [key: string]: string;
            };
            /** @description 兼容旧客户端的中文欢迎语 */
            message?: string;
        };
        CurrentUserData: {
            /** Format: int64 */
            userId: number;
            /** Format: int64 */
            studentId?: number | null;
            username: string;
            displayName: string;
            userType: string;
            welcome?: components["schemas"]["WelcomeData"] | null;
        };
        LoginData: {
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /** Format: int64 */
            expiresInSeconds: number;
            user: components["schemas"]["CurrentUserData"];
        };
        LoginSuccessResponse: components["schemas"]["ApiResponseMetadata"] & {
            data: components["schemas"]["LoginData"];
            error?: Record<string, never> | null;
        };
        ErrorDetail: {
            code: string;
            message: string;
        };
        ErrorResponse: components["schemas"]["ApiResponseMetadata"] & {
            data?: Record<string, never> | null;
            error: components["schemas"]["ErrorDetail"];
        };
        ActivateRequest: {
            studentNumber: string;
            studentName: string;
            password: string;
        };
        VoidSuccessResponse: components["schemas"]["ApiResponseMetadata"] & {
            data?: Record<string, never> | null;
            error?: Record<string, never> | null;
        };
        CurrentUserSuccessResponse: components["schemas"]["ApiResponseMetadata"] & {
            data: components["schemas"]["CurrentUserData"];
            error?: Record<string, never> | null;
        };
        ObjectSuccessResponse: components["schemas"]["ApiResponseMetadata"] & {
            data: {
                [key: string]: unknown;
            };
            error?: Record<string, never> | null;
        };
        StudentWelcomeSettingUpdateRequest: {
            messages: {
                [key: string]: string;
            };
            /** Format: int32 */
            expectedVersion: number;
        };
        ListSuccessResponse: components["schemas"]["ApiResponseMetadata"] & {
            data: {
                [key: string]: unknown;
            }[];
            error?: Record<string, never> | null;
        };
        MajorRequest: {
            majorCode: string;
            majorName: string;
            enabled: boolean;
        };
        StudentRequest: {
            studentNumber: string;
            studentName: string;
            gender: string;
            /** Format: int64 */
            majorId: number;
            /** @default CN */
            nationalityCode: string;
            phoneNumber?: string;
        };
        RoomRequest: {
            capacity: number;
            gender: string;
            operationalStatus: string;
            remark?: string;
            reason: string;
        };
        RoomBedLayoutItem: {
            /** Format: int64 */
            bedId: number;
            /** @enum {string} */
            bedType: "LOFT_BED_DESK" | "BUNK";
            /** Format: double */
            layoutX: number;
            /** Format: double */
            layoutZ: number;
            /**
             * Format: int32
             * @enum {integer}
             */
            rotationDegrees: 0 | 90 | 180 | 270;
        };
        RoomBedLayoutRequest: {
            /** Format: int64 */
            expectedRoomVersion: number;
            reason: string;
            beds: components["schemas"]["RoomBedLayoutItem"][];
        };
        MatchingWeightSchemeCreateRequest: {
            schemeCode: string;
            schemeName: string;
            algorithmVersion: string;
            weights: {
                [key: string]: number;
            };
            conflictRules: {
                [key: string]: number;
            };
            activate: boolean;
            reason: string;
        };
        MatchingWeightSchemeRevisionRequest: {
            schemeName: string;
            algorithmVersion: string;
            weights: {
                [key: string]: number;
            };
            conflictRules: {
                [key: string]: number;
            };
            activate: boolean;
            /** Format: int32 */
            expectedVersion: number;
            reason: string;
        };
        BatchRequest: {
            batchCode: string;
            batchName: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            holdDurationSeconds: number;
            allowTeam: boolean;
            teamMaxSize: number;
            allowStudentRandom: boolean;
        };
        BatchCopyRequest: {
            batchCode: string;
            batchName: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            reason: string;
        };
        AllocationCommitRequest: {
            /** Format: int64 */
            randomSeed: number;
            idempotencyKey: string;
        };
        AssignmentAdjustmentRequest: {
            /** Format: int64 */
            newBedId: number;
            reason: string;
        };
        StudentPhoneUpdateRequest: {
            phoneNumber: string;
        };
        HoldTokenRequest: {
            token: string;
        };
        InviteRequest: {
            studentNumber: string;
        };
        InvitationResponseRequest: {
            invitationToken: string;
            accepted: boolean;
        };
        TeamBedsRequest: {
            bedIds: number[];
        };
        TeamConfirmRequest: components["schemas"]["TeamBedsRequest"] & {
            token: string;
        };
    };
    responses: {
        /** @description 业务错误 */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 操作成功 */
        ObjectSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ObjectSuccessResponse"];
            };
        };
        /** @description 查询成功 */
        ListSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ListSuccessResponse"];
            };
        };
        /** @description 操作成功 */
        VoidSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["VoidSuccessResponse"];
            };
        };
    };
    parameters: {
        IdPath: number;
        RoomIdPath: number;
        BatchIdPath: number;
        NotificationIdPath: number;
        BedIdPath: number;
        TeamIdPath: number;
        StudentIdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginSuccessResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateRequest"];
            };
        };
        responses: {
            /** @description 激活成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidSuccessResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 退出成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidSuccessResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserSuccessResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    acknowledgeStudentWelcome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 确认成功；重复调用保持幂等 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidSuccessResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    getStudentWelcomeSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前欢迎语配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectSuccessResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    updateStudentWelcomeSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentWelcomeSettingUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的欢迎语配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectSuccessResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    listMajors: {
        parameters: {
            query?: {
                enabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    createMajor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MajorRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    updateMajor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MajorRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listStudents: {
        parameters: {
            query?: {
                keyword?: string;
                gender?: string;
                majorId?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    updateStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    importStudents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentRequest"][];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
        };
    };
    listBuildings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    listRooms: {
        parameters: {
            query?: {
                buildingId?: number;
                gender?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    updateRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomRequest"];
            };
        };
        responses: {
            200: components["responses"]["VoidSuccess"];
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    getRoomBedLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    updateRoomBedLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomBedLayoutRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    listMatchingWeightSchemes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSuccessResponse"];
                };
            };
        };
    };
    createMatchingWeightScheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchingWeightSchemeCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectSuccessResponse"];
                };
            };
            /** @description 配置校验失败 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 方案编码冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createMatchingWeightSchemeRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schemeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchingWeightSchemeRevisionRequest"];
            };
        };
        responses: {
            /** @description 新修订创建成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectSuccessResponse"];
                };
            };
            /** @description 配置校验失败 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 原方案不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 原方案版本已变化 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listBatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    createBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
        };
    };
    copyBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCopyRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    prepareBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
        };
    };
    changeBatchStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
                targetStatus: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["VoidSuccess"];
            400: components["responses"]["ErrorResponse"];
        };
    };
    previewAllocation: {
        parameters: {
            query?: {
                randomSeed?: number;
            };
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
        };
    };
    commitAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationCommitRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    listAssignments: {
        parameters: {
            query?: {
                keyword?: string;
            };
            header?: never;
            path: {
                batchId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前有效分配列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSuccessResponse"];
                };
            };
            /** @description 批次不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adjustAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentAdjustmentRequest"];
            };
        };
        responses: {
            /** @description 调整成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectSuccessResponse"];
                };
            };
            /** @description 参数或业务规则错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 分配或床位不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目标床位已分配 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    exportAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分配结果CSV文件 */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    getStudentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
        };
    };
    updateStudentPhoneNumber: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentPhoneUpdateRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: components["parameters"]["NotificationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["VoidSuccess"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listStudentBatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    getQuestionnaire: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
        };
    };
    submitQuestionnaire: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: components["responses"]["VoidSuccess"];
            400: components["responses"]["ErrorResponse"];
        };
    };
    listCandidateRooms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    getCandidateRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
                roomId: components["parameters"]["RoomIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    preparePersonalSelection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    holdBed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
                bedId: components["parameters"]["BedIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    releaseBed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
                bedId: components["parameters"]["BedIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldTokenRequest"];
            };
        };
        responses: {
            200: components["responses"]["VoidSuccess"];
        };
    };
    confirmBed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
                bedId: components["parameters"]["BedIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldTokenRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    getRandomRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
        };
    };
    getMyAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
        };
    };
    listMyTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    listTeamInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListSuccess"];
        };
    };
    inviteTeammate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    respondTeamInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationResponseRequest"];
            };
        };
        responses: {
            200: components["responses"]["VoidSuccess"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    lockTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    leaveTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    removeTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["TeamIdPath"];
                studentId: components["parameters"]["StudentIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ObjectSuccess"];
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    holdTeamBeds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
                teamId: components["parameters"]["TeamIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamBedsRequest"];
            };
        };
        responses: {
            200: components["responses"]["ObjectSuccess"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    releaseTeamBeds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: number;
                teamId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamConfirmRequest"];
            };
        };
        responses: {
            /** @description 释放成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidSuccessResponse"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmTeamBeds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchIdPath"];
                teamId: components["parameters"]["TeamIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamConfirmRequest"];
            };
        };
        responses: {
            200: components["responses"]["VoidSuccess"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    subscribeRoomEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                batchId: number;
                roomId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务器发送事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
}
