<script setup lang="ts">
import { computed, ref } from 'vue'
import type { DataObject } from '../../../api/types'
import AppModal from '../../../components/modal/AppModal.vue'
import { compareTableValues, type SortDirection } from '../../../composables/useTableSort'

type SelectOption = { id: string; label: string }
const props = defineProps<{
  open:boolean;scopeBatch:DataObject|null;scopeLoading:boolean;scopeSaving:boolean;selectedStudentIds:number[];selectedRoomIds:number[];studentFilter:string;studentGenderFilter:string;studentCategoryFilter:string;studentDegreeFilter:string;studentMajorFilter:string;studentGradeFilter:string;roomFilter:string;roomGenderFilter:string;roomScopeFilter:string;roomBuildingFilter:string;roomFloorFilter:string;scopeMajorOptions:SelectOption[];scopeGradeOptions:string[];scopeBuildingOptions:SelectOption[];scopeFloorOptions:string[];filteredStudents:DataObject[];filteredRooms:DataObject[];publishAfterScope:boolean;publishFlowState:string;publishFlowBusy:boolean;runningPreflight:boolean
}>()
const emit = defineEmits<{
  close:[];'toggle-student':[studentId:number];'toggle-room':[roomId:number];'select-all-students':[];'clear-students':[];'select-all-rooms':[];'clear-rooms':[];'update:student-filter':[value:string];'update:student-gender-filter':[value:string];'update:student-category-filter':[value:string];'update:student-degree-filter':[value:string];'update:student-major-filter':[value:string];'update:student-grade-filter':[value:string];'update:room-filter':[value:string];'update:room-gender-filter':[value:string];'update:room-scope-filter':[value:string];'update:room-building-filter':[value:string];'update:room-floor-filter':[value:string];save:[];'save-and-publish':[]
}>()
const studentSortField=ref('student_number');const studentSortDirection=ref<SortDirection>('asc');const roomSortField=ref('building_name');const roomSortDirection=ref<SortDirection>('asc')
function sortRows(rows:DataObject[],field:string,direction:SortDirection){if(!field||!direction)return rows;const factor=direction==='asc'?1:-1;return rows.map((row,index)=>({row,index})).sort((a,b)=>compareTableValues(a.row[field],b.row[field])*factor||a.index-b.index).map(item=>item.row)}
const sortedStudents=computed(()=>sortRows(props.filteredStudents,studentSortField.value,studentSortDirection.value))
const sortedRooms=computed(()=>sortRows(props.filteredRooms,roomSortField.value,roomSortDirection.value))
</script>

<template>
  <AppModal :open="open" :title="`${scopeBatch?.batch_name??'批次'} · 参与范围`" description="学生与宿舍均可按不同字段升序或降序排列。" size="large" max-height="94dvh" :busy="scopeLoading" :prevent-close="publishFlowBusy||publishFlowState==='WAITING_CONFIRMATION'" @close="emit('close')">
    <template v-if="!scopeLoading">
      <div class="scope-summary"><article><span>已选学生</span><strong>{{ selectedStudentIds.length }}</strong></article><article><span>已选宿舍</span><strong>{{ selectedRoomIds.length }}</strong></article></div>
      <div class="scope-grid">
        <section class="scope-column"><header class="scope-column-header"><div><strong>参与学生</strong><small>按学号、姓名、专业和学生属性筛选排序</small></div><div class="button-row"><button class="button ghost small" @click="emit('select-all-students')">全选当前结果</button><button class="button ghost small" @click="emit('clear-students')">清空</button></div></header>
          <div class="scope-filter-panel scope-filter-grid"><input :value="studentFilter" class="input span-2" placeholder="搜索学号、姓名或专业" @input="emit('update:student-filter',($event.target as HTMLInputElement).value.trim())" /><select :value="studentGenderFilter" class="input" @change="emit('update:student-gender-filter',($event.target as HTMLSelectElement).value)"><option value="">全部性别</option><option value="M">男生</option><option value="F">女生</option></select><select :value="studentCategoryFilter" class="input" @change="emit('update:student-category-filter',($event.target as HTMLSelectElement).value)"><option value="">国内外不限</option><option value="DOMESTIC">国内生</option><option value="INTERNATIONAL">国际生</option></select><select :value="studentDegreeFilter" class="input" @change="emit('update:student-degree-filter',($event.target as HTMLSelectElement).value)"><option value="">培养层次不限</option><option value="UNDERGRADUATE">本科生</option><option value="MASTER">硕士生</option><option value="DOCTOR">博士生</option><option value="MASTER_DOCTOR">硕博生</option></select><select :value="studentMajorFilter" class="input" @change="emit('update:student-major-filter',($event.target as HTMLSelectElement).value)"><option value="">全部专业</option><option v-for="major in scopeMajorOptions" :key="major.id" :value="major.id">{{ major.label }}</option></select><select :value="studentGradeFilter" class="input span-2" @change="emit('update:student-grade-filter',($event.target as HTMLSelectElement).value)"><option value="">全部年级</option><option v-for="grade in scopeGradeOptions" :key="grade" :value="grade">{{ grade }}级</option></select></div>
          <div class="scope-sort-row"><select v-model="studentSortField" class="input"><option value="student_number">按学号</option><option value="student_name">按姓名</option><option value="major_name">按专业</option><option value="grade_year">按年级</option><option value="student_category">按学生类别</option></select><select v-model="studentSortDirection" class="input"><option value="asc">升序</option><option value="desc">降序</option></select></div>
          <div class="scope-result-summary"><span>筛选结果 {{ sortedStudents.length }} 人</span><span>已选择 {{ selectedStudentIds.length }} 人</span></div><div class="scope-result-list"><label v-for="student in sortedStudents" :key="String(student.id)" class="scope-option"><input type="checkbox" :checked="selectedStudentIds.includes(Number(student.id))" @change="emit('toggle-student',Number(student.id))" /><div><strong>{{ student.student_number }} · {{ student.student_name }}</strong><span>{{ student.major_name }} · {{ student.gender==='M'?'男':'女' }} · {{ student.student_category==='INTERNATIONAL'?'国际生':'国内生' }}</span></div></label><p v-if="!sortedStudents.length" class="empty-state compact">没有符合当前条件的学生。</p></div>
        </section>
        <section class="scope-column"><header class="scope-column-header"><div><strong>可选宿舍</strong><small>停用、维护或不符合批次规则的宿舍不可选择</small></div><div class="button-row"><button class="button ghost small" @click="emit('select-all-rooms')">全选当前可用</button><button class="button ghost small" @click="emit('clear-rooms')">清空</button></div></header>
          <div class="scope-filter-panel scope-filter-grid"><input :value="roomFilter" class="input span-2" placeholder="搜索楼栋、楼层或房间号" @input="emit('update:room-filter',($event.target as HTMLInputElement).value.trim())" /><select :value="roomGenderFilter" class="input" @change="emit('update:room-gender-filter',($event.target as HTMLSelectElement).value)"><option value="">全部性别</option><option value="M">男寝</option><option value="F">女寝</option></select><select :value="roomScopeFilter" class="input" @change="emit('update:room-scope-filter',($event.target as HTMLSelectElement).value)"><option value="">国内外不限</option><option value="DOMESTIC_ONLY">国内生宿舍</option><option value="INTERNATIONAL_ONLY">国际生宿舍</option><option value="MIXED">混住宿舍</option></select><select :value="roomBuildingFilter" class="input" @change="emit('update:room-building-filter',($event.target as HTMLSelectElement).value)"><option value="">全部楼栋</option><option v-for="building in scopeBuildingOptions" :key="building.id" :value="building.id">{{ building.label }}</option></select><select :value="roomFloorFilter" class="input" @change="emit('update:room-floor-filter',($event.target as HTMLSelectElement).value)"><option value="">全部楼层</option><option v-for="floor in scopeFloorOptions" :key="floor" :value="floor">{{ floor }}层</option></select></div>
          <div class="scope-sort-row"><select v-model="roomSortField" class="input"><option value="building_name">按楼栋</option><option value="room_number">按寝室号</option><option value="floor_number">按楼层</option><option value="capacity">按容量</option><option value="operational_status">按运行状态</option></select><select v-model="roomSortDirection" class="input"><option value="asc">升序</option><option value="desc">降序</option></select></div>
          <div class="scope-result-summary"><span>筛选结果 {{ sortedRooms.length }} 间</span><span>已选择 {{ selectedRoomIds.length }} 间</span></div><div class="scope-result-list"><label v-for="room in sortedRooms" :key="String(room.id)" class="scope-option" :class="{disabled:!room.selectable}"><input type="checkbox" :disabled="!room.selectable" :checked="selectedRoomIds.includes(Number(room.id))" @change="emit('toggle-room',Number(room.id))" /><div><strong>{{ room.building_name }} {{ room.room_number }}</strong><span>{{ room.floor_number }}层 · 容量{{ room.capacity }} · {{ room.gender_restriction==='M'?'男寝':'女寝' }} · {{ room.operational_status }}</span></div></label><p v-if="!sortedRooms.length" class="empty-state compact">没有符合当前条件的宿舍。</p></div>
        </section>
      </div>
    </template>
    <template #footer><div class="scope-footer-status"><strong>{{ publishAfterScope?'需要补齐范围后继续发布':'当前状态：'+publishFlowState }}</strong><span>范围保存成功后即使发布失败也不会丢失。</span></div><button class="button ghost" :disabled="publishFlowBusy" @click="emit('close')">关闭</button><button class="button secondary" :disabled="scopeLoading||publishFlowBusy" @click="emit('save')">{{ scopeSaving?'保存中…':'仅保存范围' }}</button><button class="button primary" :disabled="scopeLoading||publishFlowBusy" @click="emit('save-and-publish')">{{ scopeSaving||runningPreflight?'正在准备发布…':'保存并发布' }}</button></template>
  </AppModal>
</template>

<style scoped>
.scope-summary{display:grid;grid-template-columns:repeat(2,minmax(0,180px));gap:12px;margin-bottom:14px}.scope-summary article{padding:14px;border-radius:12px;background:var(--surface-soft)}.scope-summary strong{display:block;font-size:24px}.scope-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);align-items:start;gap:16px}.scope-column{display:flex;flex-direction:column;gap:12px;min-width:0;padding:14px;border:1px solid var(--border);border-radius:14px;background:var(--surface-soft)}.scope-column-header{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.scope-column-header small{display:block;margin-top:4px;color:var(--text-muted)}.scope-filter-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.scope-filter-grid .span-2{grid-column:span 2}.scope-sort-row{display:grid;grid-template-columns:1fr 120px;gap:8px}.scope-result-summary{display:flex;justify-content:space-between;gap:10px;padding:9px 11px;border-radius:10px;background:var(--surface);color:var(--text-muted);font-size:12px;font-weight:700}.scope-result-list{display:grid;gap:8px;min-height:160px;max-height:440px;overflow:auto;padding-right:4px}.scope-option{display:flex;gap:10px;align-items:flex-start;padding:11px;border:1px solid var(--border);border-radius:11px;background:var(--surface)}.scope-option input{margin-top:4px}.scope-option div{display:grid;gap:3px}.scope-option span{color:var(--text-muted);font-size:12px}.scope-option.disabled{opacity:.55}.scope-footer-status{display:grid;gap:3px;margin-right:auto;max-width:420px;color:var(--text-muted);font-size:12px}.scope-footer-status strong{color:var(--text)}@media(max-width:900px){.scope-grid{grid-template-columns:1fr}.scope-result-list{max-height:320px}}@media(max-width:720px){.scope-filter-grid,.scope-sort-row{grid-template-columns:1fr}.scope-filter-grid .span-2{grid-column:auto}.scope-summary{grid-template-columns:1fr}.scope-column-header{flex-direction:column}}
</style>
