<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ActionConfirmDialog from '../../components/common/ActionConfirmDialog.vue'
import { api, subscribeRoomEvents } from '../../api/client'
import type { DataObject, ListSuccessResponse, ObjectSuccessResponse } from '../../api/types'

const route=useRoute();const router=useRouter();const batchId=Number(route.params.batchId);const teamId=route.query.teamId?Number(route.query.teamId):null;const isTeamMode=computed(()=>Boolean(teamId));const memberCount=Number(route.query.memberCount??1)
const rooms=ref<DataObject[]>([]);const buildings=ref<DataObject[]>([]);const buildingId=ref<number|undefined>();const floorNumber=ref<number|undefined>();const roomType=ref('');const residentScope=ref('');const loading=ref(false);const error=ref('');const showPersonalConfirm=ref(false);const personalPreparing=ref(false);const abortController=new AbortController()
const filteredRooms=computed(()=>rooms.value.filter(room=>(!buildingId.value||Number(room.building_id)===buildingId.value)&&(!floorNumber.value||Number(room.floor_number)===floorNumber.value)&&(!roomType.value||String(room.room_type)===roomType.value)&&(!residentScope.value||String(room.resident_scope)===residentScope.value)))
const floors=computed(()=>[...new Set(rooms.value.filter(room=>!buildingId.value||Number(room.building_id)===buildingId.value).map(room=>Number(room.floor_number)))].sort((a,b)=>a-b))
onMounted(async()=>{await load();void subscribeRoomEvents(batchId,null,abortController.signal,event=>{if(!['HEARTBEAT','CONNECTED'].includes(event.event))void load(false)}).catch(reason=>{if(!abortController.signal.aborted)error.value=reason instanceof Error?reason.message:'房间列表实时更新连接已中断'})})
onBeforeUnmount(()=>abortController.abort());watch(buildingId,()=>{floorNumber.value=undefined})
async function load(showLoading=true){if(showLoading)loading.value=true;error.value='';try{const [roomResponse,buildingResponse]=await Promise.all([api.get<ListSuccessResponse>(`/api/v1/student/batches/${batchId}/rooms`),api.get<ListSuccessResponse>('/api/v1/student/buildings')]);rooms.value=(roomResponse.data.data??[]) as DataObject[];buildings.value=(buildingResponse.data.data??[]) as DataObject[]}catch(reason){error.value=reason instanceof Error?reason.message:'房间列表加载失败'}finally{loading.value=false}}
function openRoom(room:DataObject){void router.push({path:`/student/batches/${batchId}/rooms/${room.id}`,query:teamId?{teamId:String(teamId),memberCount:String(memberCount)}:{}})}
function requestPersonalSelection(){showPersonalConfirm.value=true}
async function preparePersonalSelection(){if(personalPreparing.value)return;personalPreparing.value=true;error.value='';try{await api.post(`/api/v1/student/batches/${batchId}/personal-selection/prepare`);showPersonalConfirm.value=false;await router.replace({path:`/student/batches/${batchId}/rooms`})}catch(reason){error.value=reason instanceof Error?reason.message:'退出队伍并进入个人选寝失败'}finally{personalPreparing.value=false}}
function roomTypeText(value:unknown){return({FOUR_PERSON:'四人间',FIVE_PERSON:'五人间',SIX_PERSON:'六人间',OTHER:'其他'} as Record<string,string>)[String(value)]??String(value)}
function scopeText(value:unknown){return({DOMESTIC_ONLY:'国内生',INTERNATIONAL_ONLY:'国际生',MIXED:'国内/国际混合'} as Record<string,string>)[String(value)]??String(value)}
</script>

<template>
  <div class="content-column room-list-page"><div class="page-title split-title"><div><span class="eyebrow">ROOM SELECTION</span><h2>{{ isTeamMode?'组队选择寝室':'选择寝室' }}</h2><p v-if="isTeamMode">当前以队长身份为 {{ memberCount }} 名已确认成员选择同一间寝室。</p><p v-else>筛选楼栋、楼层和房型后进入房间选择床位。</p></div><button v-if="!isTeamMode" class="button ghost" type="button" @click="requestPersonalSelection">退出现有队伍并个人选寝</button></div><p v-if="error" class="alert error">{{ error }}</p>
    <section class="panel room-filter-panel"><div class="room-filter-grid"><label><span>楼栋</span><select v-model="buildingId" class="input"><option :value="undefined">全部楼栋</option><option v-for="building in buildings" :key="String(building.id)" :value="Number(building.id)">{{ building.building_name }}</option></select></label><label><span>楼层</span><select v-model="floorNumber" class="input"><option :value="undefined">全部楼层</option><option v-for="floor in floors" :key="floor" :value="floor">{{ floor }}层</option></select></label><label><span>房型</span><select v-model="roomType" class="input"><option value="">全部房型</option><option value="FOUR_PERSON">四人间</option><option value="FIVE_PERSON">五人间</option><option value="SIX_PERSON">六人间</option><option value="OTHER">其他</option></select></label><label><span>学生类别</span><select v-model="residentScope" class="input"><option value="">不限</option><option value="DOMESTIC_ONLY">国内生</option><option value="INTERNATIONAL_ONLY">国际生</option><option value="MIXED">混合</option></select></label></div></section>
    <p v-if="loading" class="panel empty-state">正在同步可选寝室…</p><section v-else class="room-card-grid"><button v-for="room in filteredRooms" :key="String(room.id)" class="panel room-selection-card" type="button" :disabled="Number(room.available_bed_count??0)<(isTeamMode?memberCount:1)" @click="openRoom(room)"><div class="room-card-title"><div><span class="eyebrow">{{ room.building_name }} · {{ room.floor_number }}层</span><h3>{{ room.room_number }}室</h3></div><span class="availability-bubble">可用{{ room.available_bed_count??0 }}床</span></div><p>{{ roomTypeText(room.room_type) }} · {{ scopeText(room.resident_scope) }}</p><small v-if="isTeamMode&&Number(room.available_bed_count??0)<memberCount">可用床位不足以容纳全部已确认成员</small><small v-else>进入房间选择具体床位</small></button><p v-if="!filteredRooms.length" class="panel empty-state">没有符合当前筛选条件的寝室。</p></section>
    <ActionConfirmDialog :open="showPersonalConfirm" title="确认改为个人选寝" message="继续后将退出当前队伍，并取消与队伍相关的待处理邀请。" detail="退出完成后才能以个人身份选择寝室和床位。" confirm-text="退出队伍并继续" danger :busy="personalPreparing" @cancel="showPersonalConfirm=false" @confirm="preparePersonalSelection" />
  </div>
</template>

<style scoped>
.room-filter-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.room-filter-grid label{display:grid;gap:5px}.room-card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.room-selection-card{display:grid;gap:10px;color:inherit;text-align:left;cursor:pointer}.room-selection-card:disabled{cursor:not-allowed;opacity:.55}.room-card-title{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.room-card-title h3{margin:4px 0 0}.availability-bubble{padding:5px 9px;border-radius:999px;background:#ecfdf3;color:#147d46;font-size:12px;font-weight:800}.room-selection-card p,.room-selection-card small{margin:0;color:var(--text-muted)}@media(max-width:780px){.room-filter-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.room-filter-grid{grid-template-columns:1fr}}
</style>
