#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
python3 "$ROOT_DIR/scripts/ci/test_backend_layering.py"
python3 "$ROOT_DIR/scripts/ci/test_site_metadata_openapi_contract.py"
python3 "$ROOT_DIR/scripts/ci/test_debug_login_password_ui.py"
python3 "$ROOT_DIR/scripts/ci/test_no_embedded_sql.py"
python3 "$ROOT_DIR/scripts/ci/test_sql_performance_governance.py"
python3 "$ROOT_DIR/scripts/ci/test_student_room_recommendation_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_backend_modularization_boundaries.py"
python3 "$ROOT_DIR/scripts/ci/test_platform_controller_split.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_governance_controller_split.py"
python3 "$ROOT_DIR/scripts/ci/test_spreadsheet_support_componentization.py"
python3 "$ROOT_DIR/scripts/ci/test_system_setting_normalization_componentization.py"
python3 "$ROOT_DIR/scripts/ci/test_mybatis_foundation.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_catalog_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_major_building_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_student_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_student_admin_detailed_query_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_room_occupancy_snapshot_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_residency_snapshot_read_model.py"
python3 "$ROOT_DIR/scripts/ci/test_reference_data_redis_cache.py"
python3 "$ROOT_DIR/scripts/ci/test_reference_data_cache_v2.py"
python3 "$ROOT_DIR/scripts/ci/test_notification_dispatch_componentization.py"
python3 "$ROOT_DIR/scripts/ci/test_bed_confirmation_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_room_management_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_import_mutation_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_residency_service_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_room_change_service_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_room_exchange_service_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_batch_copy_mybatis_componentization.py"
python3 "$ROOT_DIR/scripts/ci/test_verified_team_invitation_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_entitlement_admin_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_batch_analytics_snapshot_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_matching_scheme_mybatis_cache.py"
python3 "$ROOT_DIR/scripts/ci/test_student_selection_bootstrap.py"
python3 "$ROOT_DIR/scripts/ci/test_room_selection_bootstrap.py"
python3 "$ROOT_DIR/scripts/ci/test_bed_selection_hot_path.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_dashboard_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_service_scope_convergence.py"
python3 "$ROOT_DIR/scripts/ci/test_room_layout_componentization.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_allocation_architecture.py"
python3 "$ROOT_DIR/scripts/ci/test_optimized_allocation_architecture.py"
python3 "$ROOT_DIR/scripts/ci/test_recent_audit_log_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_building_room_contract_sync.py"
python3 "$ROOT_DIR/scripts/ci/test_room_update_contract_sync.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_batch_catalog_mybatis.py"
python3 "$ROOT_DIR/scripts/ci/test_openapi_relative_refs.py"
python3 "$ROOT_DIR/scripts/ci/validate_system_contracts_v25.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_residency_building_alias.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_phase2_phase3_operations.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_import_recovery_anomaly_workflows.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_welcome_brand_room_exchange.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_waitlist_core.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_v25_integrated_workflow.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_admin_scope_questionnaire_team_ux.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_ui_business_closure.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_requested_ui_regressions.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_requested_residency_governance_regressions.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_runtime_regressions_20260807.py"
python3 "$ROOT_DIR/scripts/ci/test_dormitory_admin_student_flow.py"
python3 "$ROOT_DIR/scripts/ci/test_modal_component_behavior.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_common_modal_batch_publish.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_ui_layout_restoration.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_entitlement_recommendation_concurrency.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_audit_notification_analytics.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_governance_openapi.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_governance_schema_alignment.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_admin_runtime_governance_ui.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_admin_operations_componentization.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_admin_governance_audit_componentization.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_admin_governance_notification_analytics_componentization.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_admin_governance_report_retention_componentization.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_frontend_modularization_boundaries.py"
python3 "$ROOT_DIR/scripts/ci/test_admin_batch_create_copy_componentization.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_admin_batch_scope_preflight_componentization.py" "$ROOT_DIR"
python3 "$ROOT_DIR/scripts/ci/test_dormitory_login_preference_ui.py"
python3 "$ROOT_DIR/scripts/ci/test_building_floor_name_contract.py"
python3 "$ROOT_DIR/scripts/ci/test_room_pagination_and_exchange_search.py" "$ROOT_DIR"
