<script setup lang="ts">
import { computed, ref } from 'vue'
import type { DataObject } from '../../../api/types'
import NotificationTemplateEditor from '../../../components/admin/NotificationTemplateEditor.vue'
import RecipientSelector from '../../../components/admin/RecipientSelector.vue'
import AppModal from '../../../components/modal/AppModal.vue'
import type { NotificationRecipientCriteria, NotificationTemplateDraft } from '../composables/useNotificationCenter'

const props=defineProps<{templateDraft:NotificationTemplateDraft;templates:DataObject[];recipientCriteria:NotificationRecipientCriteria;selectedTemplateRevisionId:string;recipientCount?:number;preview:DataObject|null;tasks:DataObject[];scheduledAt:string;canTemplateManage:boolean;canNotificationSend:boolean;canNotificationSchedule:boolean;canNotificationStatus:boolean;busy?:boolean;error?:string;message?:string}>()
const emit=defineEmits<{ 'update:template-draft':[value:NotificationTemplateDraft];'update:recipient-criteria':[value:NotificationRecipientCriteria];'update:selected-template-revision-id':[value:string];'update:scheduled-at':[value:string];'save-template':[];preflight:[];'confirm-send':[];'cancel-task':[taskId:number] }>()
const templatePickerOpen=ref(false)
const visibleTemplates=computed(()=>props.templates.slice(0,5))
const hiddenTemplateCount=computed(()=>Math.max(0,props.templates.length-5))
function selectTemplate(item:DataObject){emit('update:selected-template-revision-id',String(item.revision_id??''));emit('update:template-draft',{templateId:Number(item.id),templateCode:String(item.template_code??''),templateName:String(item.template_name??''),titleZhCn:String(item.title_zh_cn??''),contentZhCn:String(item.content_zh_cn??''),titleEnUs:String(item.title_en_us??''),contentEnUs:String(item.content_en_us??''),enabled:Boolean(item.enabled),creationReason:''});templatePickerOpen.value=false}
function newContent(){emit('update:selected-template-revision-id','');emit('update:template-draft',{templateCode:'',templateName:'',titleZhCn:'',contentZhCn:'',titleEnUs:'',contentEnUs:'',enabled:true,creationReason:''})}
</script>

<template>
  <section class="panel governance-section"><header class="section-head"><div><span class="eyebrow">NOTIFICATION</span><h3>统一通知中心</h3><p>先确定通知内容，再设置接收范围并发送；模板只是可复用的内容来源，不是发送通知的前置条件。</p></div></header><p v-if="error" class="alert error">{{ error }}</p><p v-if="message" class="alert success">{{ message }}</p>
    <div class="notification-workbench">
      <section class="notification-template-list workspace-block"><div class="workspace-title"><div><strong>1. 选择内容来源</strong><span>一行最多展示5个常用模板，其余模板从弹窗选择</span></div><div class="button-row"><button v-if="hiddenTemplateCount" class="button ghost small" type="button" @click="templatePickerOpen=true">更多模板（{{ hiddenTemplateCount }}）</button><button class="button ghost small" type="button" @click="newContent">新建空白通知</button></div></div><div class="template-strip"><button v-for="item in visibleTemplates" :key="String(item.revision_id)" class="template-revision-card" :class="{active:selectedTemplateRevisionId===String(item.revision_id)}" type="button" @click="selectTemplate(item)"><strong>{{ item.template_name }}</strong><span>{{ item.template_code }} · 修订{{ item.revision }}</span><small>{{ item.enabled?'点击后载入当前编辑器':'已停用，仅可查看内容' }}</small></button><p v-if="!templates.length" class="empty-state compact">暂无通知模板，可直接新建通知内容。</p></div></section>
      <section class="notification-editor-column workspace-block"><div class="workspace-title"><div><strong>2. 编辑通知内容</strong><span>编辑区域与欢迎语保持相同的双语编辑和光标插入逻辑</span></div><span v-if="selectedTemplateRevisionId" class="source-chip">来源：修订 {{ selectedTemplateRevisionId }}</span></div><NotificationTemplateEditor v-if="canTemplateManage||canNotificationSend" :model-value="templateDraft" :busy="busy" @update:model-value="emit('update:template-draft',$event)" @save="emit('save-template')" /><p v-else class="empty-state">当前账号没有通知编辑权限。</p></section>
      <section v-if="canNotificationSend" class="notification-recipient-column workspace-block"><div class="workspace-title"><div><strong>3. 设置接收范围并发送</strong><span>批次、专业、楼栋、年级、培养层次和学生类别均为无搜索多选</span></div><span>{{ recipientCount===undefined?'尚未预检':`预计 ${recipientCount} 人` }}</span></div><RecipientSelector :model-value="recipientCriteria" :recipient-count="recipientCount" :busy="busy" @update:model-value="emit('update:recipient-criteria',$event)" @preflight="emit('preflight')" /><div v-if="preview" class="preview-card"><div class="preview-heading"><strong>当前内容预览</strong><span>接收人 {{ preview.recipientCount }} 人</span></div><h4>{{ preview.titleZhCn }}</h4><p>{{ preview.contentZhCn }}</p><details v-if="preview.titleEnUs||preview.contentEnUs"><summary>查看英文内容</summary><h4>{{ preview.titleEnUs }}</h4><p>{{ preview.contentEnUs }}</p></details></div><label v-if="canNotificationSchedule" class="schedule-field"><span>定时发送时间（可选）</span><input class="input" type="datetime-local" :value="scheduledAt" @input="emit('update:scheduled-at',($event.target as HTMLInputElement).value)" /><small>立即发送使用当前编辑内容；定时发送需先保存为模板修订。</small></label><button class="button primary send-button" type="button" :disabled="recipientCount===undefined||!templateDraft.titleZhCn.trim()||!templateDraft.contentZhCn.trim()||busy" @click="emit('confirm-send')">{{ scheduledAt?'确认创建定时发送任务':'确认直接发送当前内容' }}</button></section>
    </div>
    <div v-if="canNotificationStatus" class="notification-task-section"><div class="workspace-title"><div><strong>发送任务</strong><span>仅定时/异步模板任务会出现在这里</span></div></div><div class="task-list"><article v-for="task in tasks" :key="String(task.id)"><strong>{{ task.task_status }}</strong><span>{{ task.recipient_count }}人 · {{ task.scheduled_at }} · {{ task.time_zone }}</span><button v-if="task.task_status==='SCHEDULED'&&canNotificationSchedule" class="button ghost small" type="button" :disabled="busy" @click="emit('cancel-task',Number(task.id))">取消</button></article><p v-if="!tasks.length" class="empty-state compact">暂无发送任务。</p></div></div>
    <AppModal :open="templatePickerOpen" title="选择通知模板" size="large" @close="templatePickerOpen=false"><div class="template-picker-grid"><button v-for="item in templates" :key="`picker-${String(item.revision_id)}`" type="button" class="template-revision-card" :class="{active:selectedTemplateRevisionId===String(item.revision_id)}" @click="selectTemplate(item)"><strong>{{ item.template_name }}</strong><span>{{ item.template_code }} · 修订{{ item.revision }}</span><small>{{ item.enabled?'可直接载入编辑':'已停用模板' }}</small></button></div></AppModal>
  </section>
</template>

<style scoped>
.governance-section{display:grid;gap:18px}.notification-workbench{display:grid;grid-template-columns:1fr;gap:16px}.workspace-block{display:grid;align-content:start;gap:14px;min-width:0;padding:18px;border:1px solid var(--border);border-radius:16px;background:var(--surface)}.workspace-title{display:flex;align-items:center;justify-content:space-between;gap:12px}.workspace-title>div{display:grid;gap:3px}.workspace-title span{color:var(--text-muted);font-size:11px}.source-chip{padding:5px 9px;border-radius:999px;background:var(--surface-soft)}.template-strip{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px;overflow:hidden}.template-revision-card{display:grid;gap:3px;min-width:0;width:100%;border:1px solid var(--border);border-radius:14px;padding:11px;background:var(--surface-soft);color:inherit;text-align:left;cursor:pointer}.template-revision-card strong,.template-revision-card span,.template-revision-card small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.template-revision-card.active{border-color:var(--primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--primary) 12%,transparent)}.template-revision-card span,.template-revision-card small{color:var(--text-muted);font-size:11px}.template-picker-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:10px;max-height:58vh;overflow:auto}.preview-card{display:grid;gap:8px;padding:15px;border:1px solid var(--border);border-radius:13px;background:var(--surface-soft)}.preview-heading{display:flex;align-items:center;justify-content:space-between;gap:10px}.preview-card h4,.preview-card p{margin:0}.preview-card p{white-space:pre-wrap;line-height:1.7}.preview-card details{display:grid;gap:7px;padding-top:8px;border-top:1px solid var(--border)}.schedule-field{display:grid;gap:6px}.schedule-field small{color:var(--text-muted)}.send-button{justify-self:start;min-width:220px}.notification-task-section{display:grid;gap:10px;padding-top:16px;border-top:1px solid var(--border)}.task-list{display:grid;gap:8px}.task-list article{display:flex;align-items:center;gap:12px;padding:11px;border:1px solid var(--border);border-radius:11px}.task-list article span{color:var(--text-muted);font-size:12px;flex:1}@media(max-width:1080px){.template-strip{grid-template-columns:repeat(3,minmax(0,1fr))}.template-strip .template-revision-card:nth-child(n+4){display:none}}@media(max-width:760px){.workspace-title,.preview-heading{align-items:flex-start;flex-direction:column}.template-strip{grid-template-columns:1fr}.template-strip .template-revision-card:nth-child(n+2){display:none}.send-button{width:100%}.task-list article{align-items:flex-start;flex-direction:column}}
</style>