-- V13: seed single system administrator, immutable feature/quota catalogs and default long-term subscription

INSERT INTO app_user (
    username, password_hash, user_type, account_status, display_name,
    password_change_required, created_at, updated_at
) VALUES (
    'system_admin',
    '$2y$10$/u8KFfHfymNrLU7g7BcDAOZZV593rMjoTXPupqzxwBOC77qGtlUr2',
    'SYSTEM_ADMIN', 'ACTIVE', '系统管理员', 1,
    CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
);

INSERT INTO feature_catalog
(feature_code, feature_name, phase, scope, granularity, action_type, risk_level, enabled_in_program, sort_order)
VALUES
('P1_IDENTITY_BASIC','基础身份与学生管理','PHASE1','ADMIN','MODULE','CONFIGURE','MEDIUM',1,100),
('P1_DORMITORY_BASIC','基础宿舍资源管理','PHASE1','ADMIN','MODULE','CONFIGURE','MEDIUM',1,110),
('P1_BATCH_BASIC','基础选寝批次管理','PHASE1','ADMIN','MODULE','CONFIGURE','HIGH',1,120),
('P1_PREFERENCE_BASIC','基础个人偏好与匹配','PHASE1','SHARED','MODULE','UPDATE','MEDIUM',1,130),
('P1_SELF_SELECTION','学生自主选床','PHASE1','STUDENT','MODULE','EXECUTE','HIGH',1,140),
('P1_TEAM_SELECTION','邀请式组队选寝','PHASE1','STUDENT','MODULE','EXECUTE','HIGH',1,150),
('P1_RANDOM_RECOMMENDATION','学生随机推荐','PHASE1','STUDENT','MODULE','EXECUTE','LOW',1,160),
('P1_UNIFIED_ALLOCATION','统一分配','PHASE1','ADMIN','MODULE','EXECUTE','HIGH',1,170),
('P1_ASSIGNMENT_MANAGEMENT','分配结果与人工调整','PHASE1','ADMIN','MODULE','UPDATE','HIGH',1,180),
('P1_REALTIME_STATUS','实时床位状态','PHASE1','SHARED','MODULE','READ','LOW',1,190),
('P1_BASIC_EXPORT_AUDIT','基础导出与审计','PHASE1','ADMIN','MODULE','EXPORT','HIGH',1,200),

('P2_ROOM_LAYOUT_VIEW','查看房间床位布局','PHASE2','ADMIN','OPERATION','READ','LOW',1,300),
('P2_ROOM_LAYOUT_UPDATE','修改房间床位布局','PHASE2','ADMIN','OPERATION','UPDATE','HIGH',1,301),
('P2_BED_TYPE_UPDATE','修改床位类型','PHASE2','ADMIN','OPERATION','UPDATE','HIGH',1,302),
('P2_BED_OPERATIONAL_STATUS_UPDATE','修改床位运行状态','PHASE2','ADMIN','OPERATION','UPDATE','HIGH',1,303),
('P2_THREE_DIMENSIONAL_SELECTION','三维床位选择','PHASE2','STUDENT','OPERATION','EXECUTE','LOW',1,304),
('P2_MATCHING_SCHEME_VIEW','查看匹配方案','PHASE2','ADMIN','OPERATION','READ','LOW',1,320),
('P2_MATCHING_SCHEME_CREATE','创建匹配方案','PHASE2','ADMIN','OPERATION','CREATE','HIGH',1,321),
('P2_MATCHING_SCHEME_REVISE','修订匹配方案','PHASE2','ADMIN','OPERATION','UPDATE','HIGH',1,322),
('P2_MATCHING_SCHEME_ACTIVATE','启用匹配方案','PHASE2','ADMIN','OPERATION','EXECUTE','HIGH',1,323),
('P2_MATCHING_CONFLICT_RULE_CONFIGURE','配置冲突规则','PHASE2','ADMIN','OPERATION','CONFIGURE','HIGH',1,324),
('P2_RECOMMENDATION_EXPLANATION','推荐解释','PHASE2','STUDENT','OPERATION','READ','LOW',1,325),
('P2_WELCOME_MESSAGE_VIEW','查看欢迎语','PHASE2','ADMIN','OPERATION','READ','LOW',1,340),
('P2_WELCOME_MESSAGE_UPDATE','修改欢迎语','PHASE2','ADMIN','OPERATION','UPDATE','MEDIUM',1,341),
('P2_MULTILINGUAL_INTERFACE','中英文界面','PHASE2','SHARED','OPERATION','READ','LOW',1,342),
('P2_STUDENT_CONTACT_SELF_UPDATE','学生自助修改手机号','PHASE2','STUDENT','OPERATION','UPDATE','MEDIUM',1,343),
('P2_STUDENT_NOTIFICATION_VIEW','学生系统通知','PHASE2','STUDENT','OPERATION','READ','LOW',1,344),
('P2_TEAM_FIVE_MEMBER','五人组队','PHASE2','STUDENT','OPERATION','EXECUTE','MEDIUM',1,360),
('P2_TEAM_MEMBER_REMOVE','队长移除成员','PHASE2','STUDENT','OPERATION','EXECUTE','MEDIUM',1,361),
('P2_TEAM_MEMBER_LEAVE','成员主动退队','PHASE2','STUDENT','OPERATION','EXECUTE','MEDIUM',1,362),
('P2_TEAM_INVITATION_CANCEL','取消未确认邀请','PHASE2','STUDENT','OPERATION','EXECUTE','LOW',1,363),
('P2_TEAM_PERSONAL_SELECTION_SWITCH','组队切换个人选寝','PHASE2','STUDENT','OPERATION','EXECUTE','HIGH',1,364),
('P2_TEAM_NOTIFICATION','组队变更通知','PHASE2','STUDENT','OPERATION','READ','LOW',1,365),
('P2_BATCH_COPY','复制选寝批次','PHASE2','ADMIN','OPERATION','CREATE','HIGH',1,380),
('P2_RULE_TEMPLATE_VIEW','查看批次规则模板','PHASE2','ADMIN','OPERATION','READ','LOW',1,381),
('P2_RULE_TEMPLATE_CREATE','创建批次规则模板','PHASE2','ADMIN','OPERATION','CREATE','HIGH',1,382),
('P2_RULE_TEMPLATE_REVISE','修订批次规则模板','PHASE2','ADMIN','OPERATION','UPDATE','HIGH',1,383),
('P2_RULE_TEMPLATE_SET_DEFAULT','设置默认规则模板','PHASE2','ADMIN','OPERATION','CONFIGURE','HIGH',1,384),
('P2_BATCH_USE_EXPLICIT_RULE_REVISION','批次引用精确规则修订','PHASE2','ADMIN','OPERATION','CONFIGURE','HIGH',1,385),

('P2_IMPORT_PRECHECK','导入预检','PHASE2','ADMIN','OPERATION','READ','MEDIUM',0,400),
('P2_IMPORT_COMMIT','提交导入','PHASE2','ADMIN','OPERATION','EXECUTE','HIGH',0,401),
('P2_IMPORT_ERROR_VIEW','查看导入错误','PHASE2','ADMIN','OPERATION','READ','MEDIUM',0,402),
('P2_IMPORT_ERROR_EXPORT','导出导入错误','PHASE2','ADMIN','OPERATION','EXPORT','MEDIUM',0,403),
('P2_IMPORT_IDEMPOTENCY','导入幂等控制','PHASE2','ADMIN','OPERATION','CONFIGURE','HIGH',0,404),
('P2_IMPORT_ROLLBACK','导入回滚','PHASE2','ADMIN','OPERATION','EXECUTE','HIGH',0,405),
('P2_SENSITIVE_DATA_VIEW','查看敏感资料','PHASE2','ADMIN','OPERATION','READ','HIGH',0,420),
('P2_SENSITIVE_DATA_EXPORT','导出敏感资料','PHASE2','ADMIN','OPERATION','EXPORT','HIGH',0,421),
('P2_EXPORT_DESENSITIZATION','导出脱敏','PHASE2','ADMIN','OPERATION','CONFIGURE','HIGH',0,422),
('P2_AUDIT_ADVANCED_QUERY','高级审计查询','PHASE2','ADMIN','OPERATION','READ','MEDIUM',0,423),
('P2_AUDIT_EXPORT','审计导出','PHASE2','ADMIN','OPERATION','EXPORT','HIGH',0,424),
('P2_OPERATION_STATISTICS','运营统计','PHASE2','ADMIN','OPERATION','READ','LOW',0,425),
('P2_BED_UTILIZATION_STATISTICS','床位利用率统计','PHASE2','ADMIN','OPERATION','READ','LOW',0,426),
('P2_UNSELECTED_STUDENT_STATISTICS','未选学生统计','PHASE2','ADMIN','OPERATION','READ','LOW',0,427),
('P2_MANUAL_ADJUSTMENT_STATISTICS','人工调整统计','PHASE2','ADMIN','OPERATION','READ','LOW',0,428),
('P2_EXCEPTION_WORKBENCH','异常处理工作台','PHASE2','ADMIN','OPERATION','EXECUTE','MEDIUM',0,429),
('P2_CONCURRENT_SELECTION_LIMIT','选寝并发限制','PHASE2','ADMIN','OPERATION','CONFIGURE','HIGH',0,440),
('P2_REDIS_RECOVERY','Redis状态恢复','PHASE2','ADMIN','OPERATION','EXECUTE','HIGH',0,441),
('P2_SELECTION_PRESSURE_TEST','选寝压力测试','PHASE2','ADMIN','OPERATION','EXECUTE','HIGH',0,442),
('P2_SLOW_QUERY_ANALYSIS','慢查询分析','PHASE2','ADMIN','OPERATION','READ','MEDIUM',0,443),
('P2_OPERATION_HEALTH_VIEW','运行健康查看','PHASE2','ADMIN','OPERATION','READ','LOW',0,444),
('P2_ALLOCATION_OPTIMIZED_PREVIEW','优化分配预演','PHASE2','ADMIN','OPERATION','READ','MEDIUM',0,460),
('P2_ALLOCATION_OPTIMIZED_EXECUTE','优化分配执行','PHASE2','ADMIN','OPERATION','EXECUTE','HIGH',0,461),
('P2_ALLOCATION_LOCAL_SWAP','分配局部交换','PHASE2','ADMIN','OPERATION','EXECUTE','HIGH',0,462),
('P2_FAIRNESS_METRIC_VIEW','公平性指标查看','PHASE2','ADMIN','OPERATION','READ','LOW',0,463),
('P2_FAIRNESS_COMPARISON','公平性方案比较','PHASE2','ADMIN','OPERATION','READ','LOW',0,464),
('P2_ALLOCATION_EXPERIMENT_EXPORT','分配实验导出','PHASE2','ADMIN','OPERATION','EXPORT','MEDIUM',0,465),

('P3_ROOM_CHANGE_REQUEST','换寝申请','PHASE3','STUDENT','OPERATION','CREATE','MEDIUM',0,600),
('P3_ROOM_CHANGE_REVIEW','换寝审核查看','PHASE3','ADMIN','OPERATION','READ','MEDIUM',0,601),
('P3_ROOM_CHANGE_APPROVE','批准换寝','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,602),
('P3_ROOM_CHANGE_REJECT','驳回换寝','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,603),
('P3_ROOM_CHANGE_EXECUTE','执行换寝','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,604),
('P3_ROOM_CHANGE_HISTORY','换寝历史','PHASE3','SHARED','OPERATION','READ','LOW',0,605),
('P3_WAITLIST_JOIN','加入候补','PHASE3','STUDENT','OPERATION','CREATE','MEDIUM',0,620),
('P3_WAITLIST_EXIT','退出候补','PHASE3','STUDENT','OPERATION','EXECUTE','LOW',0,621),
('P3_WAITLIST_RULE_CONFIGURE','配置候补规则','PHASE3','ADMIN','OPERATION','CONFIGURE','HIGH',0,622),
('P3_WAITLIST_OFFER','发出候补名额','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,623),
('P3_WAITLIST_ACCEPT','接受候补名额','PHASE3','STUDENT','OPERATION','EXECUTE','HIGH',0,624),
('P3_WAITLIST_MANUAL_ASSIGN','人工候补分配','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,625),
('P3_WAITLIST_HISTORY','候补历史','PHASE3','SHARED','OPERATION','READ','LOW',0,626),
('P3_NOTIFICATION_TEMPLATE_VIEW','查看通知模板','PHASE3','ADMIN','OPERATION','READ','LOW',0,640),
('P3_NOTIFICATION_TEMPLATE_MANAGE','管理通知模板','PHASE3','ADMIN','OPERATION','CONFIGURE','MEDIUM',0,641),
('P3_NOTIFICATION_SEND','发送通知','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,642),
('P3_NOTIFICATION_SCHEDULE','定时通知','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,643),
('P3_NOTIFICATION_DELIVERY_STATUS','通知送达状态','PHASE3','ADMIN','OPERATION','READ','LOW',0,644),
('P3_NOTIFICATION_CHANNEL_CONFIGURE','配置通知渠道','PHASE3','ADMIN','OPERATION','CONFIGURE','HIGH',0,645),
('P3_HISTORICAL_DASHBOARD','历史分析仪表盘','PHASE3','ADMIN','OPERATION','READ','LOW',0,660),
('P3_CROSS_BATCH_COMPARISON','跨批次比较','PHASE3','ADMIN','OPERATION','READ','LOW',0,661),
('P3_TREND_ANALYSIS','趋势分析','PHASE3','ADMIN','OPERATION','READ','LOW',0,662),
('P3_CUSTOM_REPORT_EXPORT','自定义报表导出','PHASE3','ADMIN','OPERATION','EXPORT','MEDIUM',0,663),
('P3_DATA_RETENTION_QUERY','数据保留查询','PHASE3','ADMIN','OPERATION','READ','MEDIUM',0,664),
('P3_MOBILE_STUDENT_ACCESS','移动学生端','PHASE3','STUDENT','OPERATION','READ','LOW',0,680),
('P3_MOBILE_ADMIN_ACCESS','移动管理端','PHASE3','ADMIN','OPERATION','READ','MEDIUM',0,681),
('P3_MOBILE_PUSH_NOTIFICATION','移动推送','PHASE3','SHARED','OPERATION','EXECUTE','MEDIUM',0,682),
('P3_BACKUP_VIEW','查看备份','PHASE3','ADMIN','OPERATION','READ','HIGH',0,700),
('P3_BACKUP_CREATE','创建备份','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,701),
('P3_BACKUP_POLICY_CONFIGURE','配置备份策略','PHASE3','ADMIN','OPERATION','CONFIGURE','HIGH',0,702),
('P3_RESTORE_PRECHECK','恢复预检','PHASE3','ADMIN','OPERATION','READ','HIGH',0,703),
('P3_RESTORE_EXECUTE','执行恢复','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,704),
('P3_DISASTER_RECOVERY_DRILL','灾难恢复演练','PHASE3','ADMIN','OPERATION','EXECUTE','HIGH',0,705),
('P3_RECOVERY_REPORT','恢复报告','PHASE3','ADMIN','OPERATION','READ','MEDIUM',0,706);

INSERT INTO quota_catalog (quota_code, quota_name, unit_name, enabled_in_program, sort_order) VALUES
('MAX_ADMIN_USERS','启用业务管理员数量','人',1,100),
('MAX_STUDENTS','学生档案数量','人',1,110),
('MAX_CAMPUSES','校区数量','个',1,120),
('MAX_BUILDINGS','宿舍楼数量','栋',1,130),
('MAX_ROOMS','房间数量','间',1,140),
('MAX_BEDS','床位数量','个',1,150),
('MAX_BATCHES_PER_YEAR','年度批次数量','次',1,160),
('MAX_CONCURRENT_ACTIVE_BATCHES','同时活动批次数量','次',1,170),
('MAX_CONCURRENT_SELECTION_USERS','并发选寝人数','人',0,180),
('MAX_IMPORT_ROWS_PER_JOB','单次导入行数','行',1,190),
('MAX_EXPORT_ROWS_PER_JOB','单次导出行数','行',1,200),
('MAX_NOTIFICATION_RECIPIENTS','单次通知人数','人',0,210),
('DATA_RETENTION_DAYS','业务数据保留天数','天',0,220),
('AUDIT_RETENTION_DAYS','审计保留天数','天',0,230),
('MAX_BACKUP_RETENTION_COUNT','备份保留份数','份',0,240);

INSERT INTO subscription_plan (plan_code, plan_name, enabled, created_by)
SELECT 'FULL_CURRENT', '当前完整功能套餐', 1, id
FROM app_user WHERE user_type='SYSTEM_ADMIN';

INSERT INTO subscription_plan_revision
(plan_id, revision, revision_name, description, enabled, change_reason, created_by)
SELECT p.id, 1, '当前完整功能套餐 V1', '兼容升级前全部已实现功能的初始化套餐', 1,
       '初始化单客户订阅与功能授权体系', u.id
FROM subscription_plan p CROSS JOIN app_user u
WHERE p.plan_code='FULL_CURRENT' AND u.user_type='SYSTEM_ADMIN';

INSERT INTO plan_revision_feature (plan_revision_id, feature_code)
SELECT pr.id, fc.feature_code
FROM subscription_plan_revision pr
JOIN subscription_plan p ON p.id=pr.plan_id
CROSS JOIN feature_catalog fc
WHERE p.plan_code='FULL_CURRENT' AND pr.revision=1 AND fc.enabled_in_program=1;

INSERT INTO plan_revision_quota (plan_revision_id, quota_code, quota_value)
SELECT pr.id, q.quota_code,
       CASE q.quota_code
           WHEN 'MAX_ADMIN_USERS' THEN 100
           WHEN 'MAX_STUDENTS' THEN 100000
           WHEN 'MAX_CAMPUSES' THEN 20
           WHEN 'MAX_BUILDINGS' THEN 1000
           WHEN 'MAX_ROOMS' THEN 100000
           WHEN 'MAX_BEDS' THEN 1000000
           WHEN 'MAX_BATCHES_PER_YEAR' THEN 1000
           WHEN 'MAX_CONCURRENT_ACTIVE_BATCHES' THEN 100
           WHEN 'MAX_IMPORT_ROWS_PER_JOB' THEN 200000
           WHEN 'MAX_EXPORT_ROWS_PER_JOB' THEN 500000
           ELSE 1000000
       END
FROM subscription_plan_revision pr
JOIN subscription_plan p ON p.id=pr.plan_id
CROSS JOIN quota_catalog q
WHERE p.plan_code='FULL_CURRENT' AND pr.revision=1;

INSERT INTO service_subscription (subscription_code) VALUES ('PRIMARY_SERVICE');

INSERT INTO service_subscription_revision
(subscription_id, revision, plan_revision_id, subscription_type, service_status,
 contract_number, start_at, end_at, signed_at, emergency_stopped,
 change_reason, remark, is_current, created_by)
SELECT s.id, 1, pr.id, 'LONG_TERM', 'ACTIVE', NULL,
       CURRENT_TIMESTAMP(3), NULL, NULL, 0,
       '初始化长期有效订阅', '默认保留升级前全部已实现业务能力', 1, u.id
FROM service_subscription s
JOIN subscription_plan p ON p.plan_code='FULL_CURRENT'
JOIN subscription_plan_revision pr ON pr.plan_id=p.id AND pr.revision=1
CROSS JOIN app_user u
WHERE s.subscription_code='PRIMARY_SERVICE' AND u.user_type='SYSTEM_ADMIN';

INSERT INTO platform_audit_log
(operation_type, operator_user_id, target_type, target_id, change_reason, after_json, success)
SELECT 'SUBSCRIPTION_CREATE', u.id, 'SERVICE_SUBSCRIPTION', CAST(s.id AS CHAR),
       '初始化长期有效订阅',
       JSON_OBJECT('subscriptionType','LONG_TERM','serviceStatus','ACTIVE','planCode','FULL_CURRENT'),
       1
FROM app_user u CROSS JOIN service_subscription s
WHERE u.user_type='SYSTEM_ADMIN' AND s.subscription_code='PRIMARY_SERVICE';
